name: Build LuaNode Firmware

on:
  workflow_dispatch:
    inputs:
      scriptPath:
        description: 'Path to the Lua script folder'
        required: true
        default: 'scripts'
      board:
        description: 'Target board'
        required: true
        default: 'GENERIC'
        type: choice

        options:
          - GENERIC
          - ESP32S3
          - ESP32C3
          - ESP32

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Clone LuaNode repository
        run: |
          git clone https://github.com/nodemcu/nodemcu-firmware.git
          cd nodemcu-firmware
          git submodule update --init --recursive

      - name: Copy Lua scripts to firmware directory
        run: |
          mkdir -p nodemcu-firmware/app/luasrc
          cp -r ${{ github.event.inputs.scriptPath }}/* nodemcu-firmware/app/luasrc/

      - name: Configure firmware for selected board
        run: |
          cd nodemcu-firmware
          make menuconfig
          # 配置目标板子和其他选项（根据 LuaNode 的 makefile 配置）
          echo "CONFIG_BOARD_${{ github.event.inputs.board }}=y" >> .config

      - name: Build LuaNode Firmware
        run: |
          cd nodemcu-firmware
          make

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: LuaNode Firmware
          path: nodemcu-firmware/bin/
